"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[99174],{603905:(e,n,t)=>{t.d(n,{Zo:()=>c,kt:()=>m});var r=t(667294);function a(e,n,t){return n in e?Object.defineProperty(e,n,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[n]=t,e}function o(e,n){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);n&&(r=r.filter((function(n){return Object.getOwnPropertyDescriptor(e,n).enumerable}))),t.push.apply(t,r)}return t}function i(e){for(var n=1;n<arguments.length;n++){var t=null!=arguments[n]?arguments[n]:{};n%2?o(Object(t),!0).forEach((function(n){a(e,n,t[n])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):o(Object(t)).forEach((function(n){Object.defineProperty(e,n,Object.getOwnPropertyDescriptor(t,n))}))}return e}function l(e,n){if(null==e)return{};var t,r,a=function(e,n){if(null==e)return{};var t,r,a={},o=Object.keys(e);for(r=0;r<o.length;r++)t=o[r],n.indexOf(t)>=0||(a[t]=e[t]);return a}(e,n);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)t=o[r],n.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(a[t]=e[t])}return a}var d=r.createContext({}),s=function(e){var n=r.useContext(d),t=n;return e&&(t="function"==typeof e?e(n):i(i({},n),e)),t},c=function(e){var n=s(e.components);return r.createElement(d.Provider,{value:n},e.children)},p={inlineCode:"code",wrapper:function(e){var n=e.children;return r.createElement(r.Fragment,{},n)}},h=r.forwardRef((function(e,n){var t=e.components,a=e.mdxType,o=e.originalType,d=e.parentName,c=l(e,["components","mdxType","originalType","parentName"]),h=s(t),m=a,u=h["".concat(d,".").concat(m)]||h[m]||p[m]||o;return t?r.createElement(u,i(i({ref:n},c),{},{components:t})):r.createElement(u,i({ref:n},c))}));function m(e,n){var t=arguments,a=n&&n.mdxType;if("string"==typeof e||a){var o=t.length,i=new Array(o);i[0]=h;var l={};for(var d in n)hasOwnProperty.call(n,d)&&(l[d]=n[d]);l.originalType=e,l.mdxType="string"==typeof e?e:a,i[1]=l;for(var s=2;s<o;s++)i[s]=t[s];return r.createElement.apply(null,i)}return r.createElement.apply(null,t)}h.displayName="MDXCreateElement"},398679:(e,n,t)=>{t.r(n),t.d(n,{assets:()=>s,contentTitle:()=>l,default:()=>h,frontMatter:()=>i,metadata:()=>d,toc:()=>c});t(667294);var r=t(603905);function a(){return a=Object.assign||function(e){for(var n=1;n<arguments.length;n++){var t=arguments[n];for(var r in t)Object.prototype.hasOwnProperty.call(t,r)&&(e[r]=t[r])}return e},a.apply(this,arguments)}function o(e,n){if(null==e)return{};var t,r,a=function(e,n){if(null==e)return{};var t,r,a={},o=Object.keys(e);for(r=0;r<o.length;r++)t=o[r],n.indexOf(t)>=0||(a[t]=e[t]);return a}(e,n);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)t=o[r],n.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(a[t]=e[t])}return a}const i={id:"error-handling",title:"Error handling"},l=void 0,d={unversionedId:"Concepts/error-handling",id:"version-20-R5/Concepts/error-handling",title:"Error handling",description:"Error handling is the process of anticipating and responding to errors that might occur in your application. 4D provides a comprehensive support for catching and reporting errors at runtime, as well as for investigating their conditions.",source:"@site/versioned_docs/version-20-R5/Concepts/error-handling.md",sourceDirName:"Concepts",slug:"/Concepts/error-handling",permalink:"/docs/Concepts/error-handling",draft:!1,editUrl:"https://github.com/4d/docs/issues/new?title=Comment%20on%20Concepts%2Ferror-handling.md%20(20-R5)&body=Please%20enter%20your%20comment%3A",tags:[],version:"20-R5",frontMatter:{id:"error-handling",title:"Error handling"},sidebar:"docs",previous:{title:"Control flow",permalink:"/docs/Concepts/control-flow"},next:{title:"Interpreted and Compiled modes",permalink:"/docs/Concepts/interpreted-compiled"}},s={},c=[{value:"Error or status",id:"error-or-status",level:2},{value:"Installing an error-handling method",id:"installing-an-error-handling-method",level:2},{value:"Scope and components",id:"scope-and-components",level:3},{value:"Handling errors within the method",id:"handling-errors-within-the-method",level:3},{value:"Example",id:"example",level:4},{value:"Using an empty error-handling method",id:"using-an-empty-error-handling-method",level:3},{value:"Try(expression)",id:"tryexpression",level:2},{value:"Examples",id:"examples",level:3},{value:"Try...Catch...End try",id:"trycatchend-try",level:2},{value:"Example",id:"example-1",level:3}],p={toc:c};function h(e){var{components:n}=e,i=o(e,["components"]);return(0,r.kt)("wrapper",a({},p,i,{components:n,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"Error handling is the process of anticipating and responding to errors that might occur in your application. 4D provides a comprehensive support for catching and reporting errors at runtime, as well as for investigating their conditions. "),(0,r.kt)("p",null,"Error handling meets two main needs:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},"finding out and fixing potential errors and bugs in your code during the development phase,"),(0,r.kt)("li",{parentName:"ul"},"catching and recovering from unexpected errors in deployed applications; in particular, you can replace system error dialogs (disk full, missing file, etc.) with you own interface. ")),(0,r.kt)("p",null,"Basically, there are two ways to handle errors in 4D. You can:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("a",a({parentName:"li"},{href:"#installing-an-error-handling-method"}),"install an error-handling method"),", or"),(0,r.kt)("li",{parentName:"ul"},"use a ",(0,r.kt)("a",a({parentName:"li"},{href:"#tryexpression"}),(0,r.kt)("inlineCode",{parentName:"a"},"Try()")," keyword")," or a ",(0,r.kt)("a",a({parentName:"li"},{href:"#trycatchend-try"}),(0,r.kt)("inlineCode",{parentName:"a"},"Try/Catch")," structure")," before pieces of code that call a function, method, or expression that can throw an error.")),(0,r.kt)("admonition",a({},{title:"Good practice",type:"tip"}),(0,r.kt)("p",{parentName:"admonition"},"It is highly recommended to install a global error-handling method on 4D Server, for all code running on the server. When 4D Server is not running ",(0,r.kt)("a",a({parentName:"p"},{href:"/docs/Admin/cli"}),"headless")," (i.e. launched with its ",(0,r.kt)("a",a({parentName:"p"},{href:"/docs/ServerWindow/overview"}),"administration window"),"), this method would avoid unexpected dialog boxes to be displayed on the server machine. In headless mode, errors are logged in the ",(0,r.kt)("a",a({parentName:"p"},{href:"/docs/Debugging/debugLogFiles#4ddebuglogtxt-standard"}),"4DDebugLog file")," for further analysis. ")),(0,r.kt)("h2",a({},{id:"error-or-status"}),"Error or status"),(0,r.kt)("p",null,"Many 4D class functions, such as ",(0,r.kt)("inlineCode",{parentName:"p"},"entity.save()")," or ",(0,r.kt)("inlineCode",{parentName:"p"},"transporter.send()"),", return a ",(0,r.kt)("em",{parentName:"p"},"status"),' object. This object is used to store "predictable" errors in the runtime context, e.g. invalid password, locked entity, etc., that do not stop program execution. This category of errors can be handled by regular code.'),(0,r.kt)("p",null,'Other "unpredictable" errors include disk write error, network failure, or in general any unexpected interruption. This category of errors generates exceptions and needs to be handled through an error-handling method or a ',(0,r.kt)("inlineCode",{parentName:"p"},"Try()")," keyword.  "),(0,r.kt)("h2",a({},{id:"installing-an-error-handling-method"}),"Installing an error-handling method"),(0,r.kt)("p",null,"In 4D, all errors can be caught and handled by specific project methods, named ",(0,r.kt)("strong",{parentName:"p"},"error-handling")," (or ",(0,r.kt)("strong",{parentName:"p"},"error-catching"),") methods. "),(0,r.kt)("p",null,"Once installed, error handlers are automatically called in interpreted or compiled mode in case of error in the 4D application or one of its components. A different error handler can be called depending on the execution context (see below).  "),(0,r.kt)("p",null,"To ",(0,r.kt)("em",{parentName:"p"},"install")," an error-handling project method, you just need to call the ",(0,r.kt)("a",a({parentName:"p"},{href:"https://doc.4d.com/4dv19/help/command/en/page155.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"ON ERR CALL"))," command with the project method name and (optionnally) scope as parameters. For example:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'ON ERR CALL("IO_Errors";ek local) //Installs a local error-handling method\n')),(0,r.kt)("p",null,"To stop catching errors for an execution context and give back hand, call ",(0,r.kt)("inlineCode",{parentName:"p"},"ON ERR CALL")," with an empty string:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'ON ERR CALL("";ek local) //gives back control for the local process\n')),(0,r.kt)("p",null,"The  ",(0,r.kt)("a",a({parentName:"p"},{href:"https://doc.4d.com/4dv20/help/command/en/page704.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"Method called on error"))," command allows you to know the name of the method installed by ",(0,r.kt)("inlineCode",{parentName:"p"},"ON ERR CALL")," for the current process. It is particularly useful in the context of generic code because it enables you to temporarily change and then restore the error-catching method:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),' $methCurrent:=Method called on error(ek local)\n ON ERR CALL("NewMethod";ek local)\n  //If the document cannot be opened, an error is generated\n $ref:=Open document("MyDocument")\n  //Reinstallation of previous method\n ON ERR CALL($methCurrent;ek local)\n\n')),(0,r.kt)("h3",a({},{id:"scope-and-components"}),"Scope and components"),(0,r.kt)("p",null,"An error-handling method can be set for different execution contexts:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},"for the ",(0,r.kt)("strong",{parentName:"li"},"current process"),"- a local error handler will be only called for errors that occurred in the current process of the current project,"),(0,r.kt)("li",{parentName:"ul"},"for the ",(0,r.kt)("strong",{parentName:"li"},"whole application"),"- a global error handler will be called for all errors that occurred in the application execution context of the current project,"),(0,r.kt)("li",{parentName:"ul"},"from the ",(0,r.kt)("strong",{parentName:"li"},"components"),"- this error handler is defined in a host project and will be called for all errors that occurred in the components when they were not already caught by a component handler.")),(0,r.kt)("p",null,"Examples:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'ON ERR CALL("IO_Errors";ek local) //Installs a local error-handling method\nON ERR CALL("globalHandler";ek global) //Installs a global error-handling method\nON ERR CALL("componentHandler";ek errors from components) //Installs an error-handling method for components\n')),(0,r.kt)("p",null,'You can install a global error handler that will serve as "fallback" and specific local error handlers for certain processes. A global error handler is also useful on the server to avoid error dialogs on the server when run with interface.'),(0,r.kt)("p",null,"You can define a single error-catching method for the whole application or different methods per application module. However, only one method can be installed per execution context and per project."),(0,r.kt)("p",null,"When an error occurs, only one method is called, as described in the following diagram:"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"error management",src:t(95813).Z,width:"1195",height:"578"})),(0,r.kt)("h3",a({},{id:"handling-errors-within-the-method"}),"Handling errors within the method"),(0,r.kt)("p",null,"Within a custom error method, you have access to several pieces of information that will help you identifying the error:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"dedicated system variables:"),(0,r.kt)("ul",{parentName:"li"},(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"Error")," (longint): error code"),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"Error method")," (text): name of the method that triggered the error"),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"Error line")," (longint): line number in the method that triggered the error"),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"Error formula")," (text): formula of the 4D code (raw text) which is at the origin of the error. ")))),(0,r.kt)("admonition",a({},{type:"info"}),(0,r.kt)("p",{parentName:"admonition"},"4D automatically maintains a number of variables called ",(0,r.kt)("strong",{parentName:"p"},"system variables"),", meeting different needs. See the ",(0,r.kt)("em",{parentName:"p"},"4D Language Reference manual"),".")),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},"the ",(0,r.kt)("a",a({parentName:"li"},{href:"https://doc.4d.com/4dv19/help/command/en/page1799.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"Last errors"))," command that returns a collection of the current stack of errors that occurred in the 4D application. You can also use the ",(0,r.kt)("a",a({parentName:"li"},{href:"https://doc.4d.com/4dv19/help/command/en/page1015.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"GET LAST ERROR STACK"))," command that returns the same information as arrays."),(0,r.kt)("li",{parentName:"ul"},"the ",(0,r.kt)("inlineCode",{parentName:"li"},"Get call chain")," command that returns a collection of objects describing each step of the method call chain within the current process. ")),(0,r.kt)("h4",a({},{id:"example"}),"Example"),(0,r.kt)("p",null,"Here is a simple error-handling system:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'//installing the error handling method\n ON ERR CALL("errorMethod")\n //... executing code\n ON ERR CALL("") //giving control back to 4D\n')),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'// errorMethod project method\n If(Error#1006) //this is not a user interruption\n    ALERT("The error "+String(Error)+" occurred". The code in question is: \\""+Error formula+"\\"")\n End if\n')),(0,r.kt)("h3",a({},{id:"using-an-empty-error-handling-method"}),"Using an empty error-handling method"),(0,r.kt)("p",null,"If you mainly want the standard error dialog box to be hidden, you can install an empty error-handling method. The ",(0,r.kt)("inlineCode",{parentName:"p"},"Error")," system variable can be tested in any method, i.e. outside of the error-handling method:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'ON ERR CALL("emptyMethod") //emptyMethod exists but is empty\n$doc:=Open document( "myFile.txt")\nIf (Error=-43)\n    ALERT("File not found.")\nEnd if\nON ERR CALL("")\n')),(0,r.kt)("h2",a({},{id:"tryexpression"}),"Try(expression)"),(0,r.kt)("p",null,"The ",(0,r.kt)("inlineCode",{parentName:"p"},"Try(expression)")," statement allows you to test a single-line expression in its actual execution context (including, in particular, local variable values) and to intercept errors it throws so that the 4D error dialog box is not displayed. Using ",(0,r.kt)("inlineCode",{parentName:"p"},"Try(expression)")," provides an easy way to handle simple error cases with a very low number of code lines, and without requiring an error-handling method. "),(0,r.kt)("admonition",a({},{type:"note"}),(0,r.kt)("p",{parentName:"admonition"},"If you want to try a more complex code than a single-line expression, you might consider using a ",(0,r.kt)("a",a({parentName:"p"},{href:"#trycatchend-try"}),(0,r.kt)("inlineCode",{parentName:"a"},"Try/Catch")," structure"),". ")),(0,r.kt)("p",null,"The formal syntax of the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try(expression)")," statement is:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),"\nTry (expression) : any | Undefined\n\n")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"expression")," can be any valid expression. "),(0,r.kt)("p",null,"If an error occurred during its execution, it is intercepted and no error dialog is displayed, whether an ",(0,r.kt)("a",a({parentName:"p"},{href:"#installing-an-error-handling-method"}),"error-handling method")," was installed or not before the call to ",(0,r.kt)("inlineCode",{parentName:"p"},"Try()"),". If ",(0,r.kt)("em",{parentName:"p"},"expression")," returns a value, ",(0,r.kt)("inlineCode",{parentName:"p"},"Try()")," returns the last evaluated value, otherwise it returns ",(0,r.kt)("inlineCode",{parentName:"p"},"Undefined"),". "),(0,r.kt)("p",null,"You can handle the error(s) using the ",(0,r.kt)("a",a({parentName:"p"},{href:"https://doc.4d.com/4dv20/help/command/en/page1799.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"Last errors"))," command. If ",(0,r.kt)("em",{parentName:"p"},"expression")," throws an error within a stack of ",(0,r.kt)("inlineCode",{parentName:"p"},"Try()")," calls, the execution flow stops and returns to the latest executed ",(0,r.kt)("inlineCode",{parentName:"p"},"Try()")," (the first found back in the call stack). "),(0,r.kt)("admonition",a({},{type:"note"}),(0,r.kt)("p",{parentName:"admonition"},"If an ",(0,r.kt)("a",a({parentName:"p"},{href:"#installing-an-error-handling-method"}),"error-handling method")," is installed by ",(0,r.kt)("em",{parentName:"p"},"expression"),", it is called in case of error. ")),(0,r.kt)("h3",a({},{id:"examples"}),"Examples"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},"You want to display the contents of a file if the file can be open without error, and if its contents can be read. You can write:")),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'var $text : Text\nvar $file : 4D.File := File("/RESOURCES/myFile.txt")\nvar $fileHandle : 4D.FileHandle := Try($file.open())\nIf ($fileHandle # Null)\n  $text:=Try($fileHandle.readText()) || "Error reading the file"\nEnd if\n')),(0,r.kt)("ol",a({},{start:2}),(0,r.kt)("li",{parentName:"ol"},"You want to handle the divide by zero error. In this case, you want to return 0 and throw an error:")),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'function divide( $p1: real; $p2: real)-> $result: real\n  if ($p2=0)\n     $result:=0 //only for clarity (0 is the default for reals)\n     throw(-12345; "Division by zero")\n  else\n    $result:=$p1/$p2\n  end if\n\nfunction test()\n  $result:=Try(divide($p1;$p2))\n  If (Last errors # null)\n    ALERT("Error")\n  End if\n\n')),(0,r.kt)("ol",a({},{start:3}),(0,r.kt)("li",{parentName:"ol"},"You want to handle both ",(0,r.kt)("a",a({parentName:"li"},{href:"#error-or-status"}),"predictable and non-predictable")," errors:")),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),'var $e:=ds.Employee.new()\n$e.name:="Smith"\n$status:=Try($e.save()) //catch predictable and non-predictable errors\nIf ($status.success)\n   ALERT( "Success")\nElse\n   ALERT( "Error: "+JSON Stringify($status.errors))\nEnd if\n\n')),(0,r.kt)("h2",a({},{id:"trycatchend-try"}),"Try...Catch...End try"),(0,r.kt)("p",null,"The ",(0,r.kt)("inlineCode",{parentName:"p"},"Try...Catch...End try")," structure allows you to test a block code in its actual execution context (including, in particular, local variable values) and to intercept errors it throws so that the 4D error dialog box is not displayed."),(0,r.kt)("p",null,"Unlike the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try(expression)")," keyword that evaluates a single-line expression, the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try...Catch...End try")," structure allows you to evaluate any code block, from the most simple to the most complex, without requiring an error-handling method. In addition, the ",(0,r.kt)("inlineCode",{parentName:"p"},"Catch")," block can be used to handle the error in any custom way. "),(0,r.kt)("p",null,"The formal syntax of the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try...Catch...End try")," structure is:"),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),"\nTry \n    statement(s) // Code to evaluate\nCatch\n    statement(s) // Code to execute in case of error\nEnd try\n\n")),(0,r.kt)("p",null,"The code placed between the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try")," and the ",(0,r.kt)("inlineCode",{parentName:"p"},"Catch")," keywords is first executed, then the flow depends on the error(s) encountered during this execution. "),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},"If no error is thrown, the code execution continues after the corresponding ",(0,r.kt)("inlineCode",{parentName:"li"},"End try")," keyword. The code placed between the ",(0,r.kt)("inlineCode",{parentName:"li"},"Catch")," and the ",(0,r.kt)("inlineCode",{parentName:"li"},"End try")," keywords is not executed."),(0,r.kt)("li",{parentName:"ul"},"If the code block execution throws a ",(0,r.kt)("em",{parentName:"li"},"non-deferred error"),", the execution flow stops and executes the corresponding ",(0,r.kt)("inlineCode",{parentName:"li"},"Catch")," code block. "),(0,r.kt)("li",{parentName:"ul"},"If the code block execution throws a ",(0,r.kt)("em",{parentName:"li"},"deferred error"),", the execution flow continues until the end of the ",(0,r.kt)("inlineCode",{parentName:"li"},"Try")," block and then executes the corresponding ",(0,r.kt)("inlineCode",{parentName:"li"},"Catch")," code block. ")),(0,r.kt)("admonition",a({},{type:"note"}),(0,r.kt)("p",{parentName:"admonition"},"If a ",(0,r.kt)("em",{parentName:"p"},"deferred")," error is thrown outside of the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try")," block, the code execution continues until the end of the method or function. ")),(0,r.kt)("admonition",a({},{type:"info"}),(0,r.kt)("p",{parentName:"admonition"},"For more information on ",(0,r.kt)("em",{parentName:"p"},"deferred")," and ",(0,r.kt)("em",{parentName:"p"},"non-deferred")," errors, please refer to the ",(0,r.kt)("a",a({parentName:"p"},{href:"https://doc.4d.com/4dv20R/help/command/en/page1805.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"throw"))," command description.")),(0,r.kt)("p",null,"In the ",(0,r.kt)("inlineCode",{parentName:"p"},"Catch")," code block, you can handle the error(s) using standard error handling commands. The ",(0,r.kt)("a",a({parentName:"p"},{href:"https://doc.4d.com/4dv20/help/command/en/page1799.html"}),(0,r.kt)("inlineCode",{parentName:"a"},"Last errors"))," function contains the last errors collection. You can ",(0,r.kt)("a",a({parentName:"p"},{href:"#installing-an-error-handling-method"}),"declare an error-handling method")," in this code block, in which case it is called in case of error (otherwise the 4D error dialog box is displayed)."),(0,r.kt)("admonition",a({},{type:"note"}),(0,r.kt)("p",{parentName:"admonition"},"If an ",(0,r.kt)("a",a({parentName:"p"},{href:"#installing-an-error-handling-method"}),"error-handling method")," is installed in the code placed between the ",(0,r.kt)("inlineCode",{parentName:"p"},"Try")," and the ",(0,r.kt)("inlineCode",{parentName:"p"},"Catch")," keywords, it is called in case of error. ")),(0,r.kt)("h3",a({},{id:"example-1"}),"Example"),(0,r.kt)("p",null,"Combining transactions and ",(0,r.kt)("inlineCode",{parentName:"p"},"Try...Catch...End try")," structures allows writing secured code for critical features. "),(0,r.kt)("pre",null,(0,r.kt)("code",a({parentName:"pre"},{className:"language-4d"}),"Function createInvoice($customer : cs.customerEntity; $items : Collection; $invoiceRef : Text) : cs.invoiceEntity\n    var $newInvoice : cs.invoiceEntity\n    var $newInvoiceLine : cs.invoiceLineEntity\n    var $item : Object\n    ds.startTransaction()\n    Try\n        $newInvoice:=This.new()\n        $newInvoice.customer:=$customer\n        $newInvoice.invoiceRef:=$invoiceRef\n        For each ($item; $items)\n            $newInvoiceLine:=ds.invoiceLine.new()\n            $newInvoiceLine.item:=$item.item\n            $newInvoiceLine.amount:=$item.amount\n            $newInvoiceLine.invoice:=$newInvoice\n            //call other specific functions to validate invoiceline\n            $newInvoiceLine.save()\n        End for each \n        $newInvoice.save()\n        ds.validateTransaction()\n    Catch\n        ds.cancelTransaction()\n        ds.logErrors(Last errors)\n        $newInvoice:=Null\n    End try\n    return $newInvoice\n\n")))}h.isMDXComponent=!0},95813:(e,n,t)=>{t.d(n,{Z:()=>r});const r=t.p+"assets/images/error-schema-973d40c4618e79de87f884622e4e930f.png"}}]);