"use strict";(self.webpackChunk=self.webpackChunk||[]).push([["44351"],{489031:function(e,r,n){n.r(r),n.d(r,{frontMatter:()=>l,toc:()=>a,default:()=>u,metadata:()=>s,assets:()=>i,contentTitle:()=>d});var s=JSON.parse('{"id":"commands-legacy/on-err-call","title":"ON ERR CALL","description":"ON ERR CALL ( m\xe9thodErreur {; port\xe9e} )","source":"@site/i18n/fr/docusaurus-plugin-content-docs/version-21/commands-legacy/on-err-call.md","sourceDirName":"commands-legacy","slug":"/commands/on-err-call","permalink":"/docs/fr/commands/on-err-call","draft":false,"unlisted":false,"editUrl":"https://github.com/4d/docs/issues/new?title=Comment%20on%20commands-legacy%2Fon-err-call.md%20(21)&body=Please%20enter%20your%20comment%3A","tags":[],"version":"21","frontMatter":{"id":"on-err-call","title":"ON ERR CALL","slug":"/commands/on-err-call","displayed_sidebar":"docs"},"sidebar":"docs","previous":{"title":"Method called on event","permalink":"/docs/fr/commands/method-called-on-event"},"next":{"title":"ON EVENT CALL","permalink":"/docs/fr/commands/on-event-call"}}'),t=n(785893),o=n(250065);let l={id:"on-err-call",title:"ON ERR CALL",slug:"/commands/on-err-call",displayed_sidebar:"docs"},d=void 0,i={},a=[{value:"Description",id:"description",level:2},{value:"Exemple 1",id:"exemple-1",level:2},{value:"Exemple 2",id:"exemple-2",level:2},{value:"Exemple 3",id:"exemple-3",level:2},{value:"Exemple 4",id:"exemple-4",level:2},{value:"Voir aussi",id:"voir-aussi",level:2},{value:"Propri\xe9t\xe9s",id:"propri\xe9t\xe9s",level:2}];function c(e){let r={a:"a",br:"br",code:"code",em:"em",h2:"h2",li:"li",p:"p",pre:"pre",strong:"strong",table:"table",tbody:"tbody",td:"td",th:"th",thead:"thead",tr:"tr",ul:"ul",...(0,o.a)(),...e.components};return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.strong,{children:"ON ERR CALL"})," ( ",(0,t.jsx)(r.em,{children:"m\xe9thodErreur"})," {; ",(0,t.jsx)(r.em,{children:"port\xe9e"}),"} )"]}),"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",(0,t.jsxs)(r.table,{children:[(0,t.jsx)(r.thead,{children:(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.th,{children:"Param\xe8tre"}),(0,t.jsx)(r.th,{children:"Type"}),(0,t.jsx)(r.th,{}),(0,t.jsx)(r.th,{children:"Description"})]})}),(0,t.jsxs)(r.tbody,{children:[(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"m\xe9thodErreur"}),(0,t.jsx)(r.td,{children:"Text"}),(0,t.jsx)(r.td,{children:"\u2192"}),(0,t.jsx)(r.td,{children:"M\xe9thode de gestion d'erreur \xe0 appeler ou Cha\xeene vide pour d\xe9sinstaller la m\xe9thode"})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"port\xe9e"}),(0,t.jsx)(r.td,{children:"Integer"}),(0,t.jsx)(r.td,{children:"\u2192"}),(0,t.jsx)(r.td,{children:"Port\xe9e de la m\xe9thode de gestion d'erreur"})]})]})]}),"\n",(0,t.jsx)(r.h2,{id:"description",children:"Description"}),"\n",(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.strong,{children:"ON ERR CALL"})," installe la m\xe9thode projet dont le nom est pass\xe9 dans ",(0,t.jsx)(r.em,{children:"m\xe9thodErreur"})," comme m\xe9thode d'interception des erreurs pour le contexte d'ex\xe9cution d\xe9fini dans le projet courant. Cette m\xe9thode est aussi appel\xe9e m\xe9thode de gestion des erreurs."]}),"\n",(0,t.jsx)(r.p,{children:"Les m\xe9thodes de gestion d'erreurs sont install\xe9es par projet : un projet composant et un projet h\xf4te peuvent d\xe9finir leur propre m\xe9thode d'interception d'erreurs, seule la m\xe9thode du projet dans lequel s'est produite l'erreur sera appel\xe9e."}),"\n",(0,t.jsx)(r.p,{children:"Apr\xe8s l'installation, 4D appelle cette m\xe9thode lorsqu'une erreur se produit lors de l'ex\xe9cution d'une commande du langage 4D dans le contexte d'ex\xe9cution d\xe9fini."}),"\n",(0,t.jsxs)(r.p,{children:["La ",(0,t.jsx)(r.em,{children:"port\xe9e"})," de la commande d\xe9signe le contexte d'ex\xe9cution depuis lequel une erreur d\xe9clenchera l'appel de ",(0,t.jsx)(r.em,{children:"m\xe9thodErreur"}),". Par d\xe9faut, si le param\xe8tre ",(0,t.jsx)(r.em,{children:"port\xe9e"})," est omis, la port\xe9e de la commande est le contexte d'ex\xe9cution local, c'est-\xe0-dire le process courant. Vous pouvez passer l'une des constantes suivantes dans le param\xe8tre ",(0,t.jsx)(r.em,{children:"port\xe9e"})," :"]}),"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",(0,t.jsxs)(r.table,{children:[(0,t.jsx)(r.thead,{children:(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.th,{children:"Constante"}),(0,t.jsx)(r.th,{children:"Valeur"}),(0,t.jsx)(r.th,{children:"Comment"})]})}),(0,t.jsxs)(r.tbody,{children:[(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"ek errors from components"}),(0,t.jsx)(r.td,{children:"2"}),(0,t.jsx)(r.td,{children:"Erreurs g\xe9n\xe9r\xe9es dans les composants (et non intercept\xe9es par les composants)"})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"ek global"}),(0,t.jsx)(r.td,{children:"1"}),(0,t.jsx)(r.td,{children:"Erreurs g\xe9n\xe9r\xe9es dans le contexte d'ex\xe9cution global du projet"})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"ek local"}),(0,t.jsx)(r.td,{children:"0"}),(0,t.jsxs)(r.td,{children:["Erreurs g\xe9n\xe9r\xe9es dans le contexte d'ex\xe9cution local (par d\xe9faut si param\xe8tre ",(0,t.jsx)(r.em,{children:"port\xe9e"})," omis)"]})]})]})]}),"\n",(0,t.jsxs)(r.ul,{children:["\n",(0,t.jsxs)(r.li,{children:["si ",(0,t.jsx)(r.em,{children:"port\xe9e"})," = ek local (ou si ",(0,t.jsx)(r.em,{children:"port\xe9e"})," est omis), seules les erreurs qui se sont produites dans le process courant appelleront m\xe9thodErreur. Il ne peut y avoir qu'une seule m\xe9thode de gestion des erreurs par process, mais il peut exister diff\xe9rentes m\xe9thodes de gestions d'erreurs pour plusieurs process."]}),"\n",(0,t.jsxs)(r.li,{children:["si ",(0,t.jsx)(r.em,{children:"port\xe9e"})," = ek global, toutes les erreurs survenues dans l'application, quel que soit le process (sauf les composants), appelleront m\xe9thodErreur. Notez que si un gestionnaire d'erreurs ek local est aussi d\xe9fini pour un process, le gestionnaire d'erreurs ek global n'est pas appel\xe9. Ce principe vous permet de d\xe9finir une m\xe9thode de gestion des erreurs g\xe9n\xe9rique qui interceptera toutes les erreurs, tandis que des m\xe9thodes locales de gestion d'erreurs peuvent \xeatre d\xe9finies pour certains process sp\xe9cifiques.",(0,t.jsx)(r.br,{}),"\nNotez \xe9galement qu'une m\xe9thode globale de gestion des erreurs est utile sur le serveur, o\xf9 elle permet de g\xe9rer les erreurs dans les fonctions c\xf4t\xe9 serveur."]}),"\n",(0,t.jsxs)(r.li,{children:["si ",(0,t.jsx)(r.em,{children:"port\xe9e"})," = ek errors from components, seules les erreurs g\xe9n\xe9r\xe9es par les composants install\xe9s dans l'application appelleront m\xe9thodErreur. Notez que, si une m\xe9thode de gestion d'erreurs est d\xe9finie dans un composant, elle est appel\xe9e en cas d'erreur dans le composant et le gestionnaire d'erreurs ek errors from components d\xe9fini dans l'application h\xf4te n'est pas appel\xe9."]}),"\n"]}),"\n",(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.strong,{children:"Note :"})," Si ",(0,t.jsx)(r.strong,{children:"ON ERR CALL"})," est appel\xe9e depuis un process dont vous avez demand\xe9 l'ex\xe9cution en pr\xe9emptif (en mode compil\xe9), le compilateur v\xe9rifiera le caract\xe8re thread-safe de ",(0,t.jsx)(r.em,{children:"m\xe9thodErreur"})," et retournera des erreurs si elle n'est pas compatible avec le mode pr\xe9emptif. Pour plus d'informations, reportez-vous \xe0 la section ",(0,t.jsx)(r.em,{children:"Process 4D pr\xe9emptifs"}),"."]}),"\n",(0,t.jsxs)(r.p,{children:["Pour d\xe9sinstaller une m\xe9thode de gestion des erreurs, appelez de nouveau ",(0,t.jsx)(r.strong,{children:"ON ERR CALL"})," avec le param\xe8tre ",(0,t.jsx)(r.em,{children:"port\xe9e"})," souhait\xe9 (le cas \xe9ch\xe9ant) et passez une cha\xeene vide dans ",(0,t.jsx)(r.em,{children:"m\xe9thodErreur"}),"."]}),"\n",(0,t.jsxs)(r.p,{children:["Vous pouvez identifier les erreurs en lisant la variable syst\xe8me Error, qui contient le code de l'erreur. Les codes d'erreurs retourn\xe9s par 4D sont trait\xe9s dans les sections ",(0,t.jsx)(r.em,{children:"Codes d'erreurs"}),". Reportez-vous par exemple \xe0 la section ",(0,t.jsx)(r.em,{children:"Erreurs de syntaxe (1 -> 81)"}),". La variable Error n'est d\xe9finie qu'\xe0 l'int\xe9rieur de la m\xe9thode de gestion des erreurs ; si vous souhaitez que le code soit accessible dans la m\xe9thode ayant provoqu\xe9 l'erreur, copiez la variable Error dans votre propre variable process. Vous pouvez \xe9galement acc\xe9der aux variables syst\xe8me Error method, Error line et Error formula contenant respectivement le nom de la m\xe9thode, le num\xe9ro de ligne et le texte de la formule \xe0 l'origine de l'erreur (cf. ",(0,t.jsx)(r.a,{href:"/docs/fr/Concepts/error-handling#g%C3%A9rer-les-erreurs-dans-une-m%C3%A9thode",children:"G\xe9rer les erreurs dans une m\xe9thode"}),")."]}),"\n",(0,t.jsxs)(r.p,{children:["Vous pouvez utiliser la commande ",(0,t.jsx)(r.a,{href:"/docs/fr/commands/last-errors",children:"Last errors"})," ou ",(0,t.jsx)(r.a,{href:"/docs/fr/commands/last-errors",children:"Last errors"}),"  pour obtenir la s\xe9quence d'erreurs (c'est-\xe0-dire la \"pile\" d'erreurs) \xe0 l'origine de l'interruption."]}),"\n",(0,t.jsx)(r.p,{children:"La m\xe9thode de gestion des erreurs doit g\xe9n\xe9ralement traiter les erreurs de mani\xe8re appropri\xe9e ou afficher un message d'erreur \xe0 l'utilisateur. Les erreurs peuvent \xeatre g\xe9n\xe9r\xe9es lors de traitements effectu\xe9s sur :"}),"\n",(0,t.jsxs)(r.ul,{children:["\n",(0,t.jsx)(r.li,{children:"Le moteur de base de donn\xe9es de 4D ; par exemple, lorsque la sauvegarde d'un enregistrement provoquerait la violation d'une r\xe8gle de trigger."}),"\n",(0,t.jsx)(r.li,{children:"L'environnement de 4D ; par exemple, lorsque vous n'avez pas assez de m\xe9moire pour remplir un tableau."}),"\n",(0,t.jsx)(r.li,{children:"Le syst\xe8me d'exploitation sur lequel la base est lanc\xe9e ; par exemple, disque plein ou erreurs d'entr\xe9e/sortie."}),"\n"]}),"\n",(0,t.jsxs)(r.p,{children:["La commande ",(0,t.jsx)(r.a,{href:"/docs/fr/commands/abort",children:"ABORT"})," peut \xeatre utilis\xe9e pour stopper le traitement. Si vous n'appelez pas ",(0,t.jsx)(r.a,{href:"/docs/fr/commands/abort",children:"ABORT"})," dans la m\xe9thode install\xe9e, 4D retourne \xe0 la m\xe9thode interrompue et reprend son ex\xe9cution. Utilisez la commande ",(0,t.jsx)(r.a,{href:"/docs/fr/commands/abort",children:"ABORT"})," lorsque l'ex\xe9cution ne peut se poursuivre."]}),"\n",(0,t.jsxs)(r.p,{children:["Si une erreur se produit dans la m\xe9thode de gestion d'erreurs elle-m\xeame, 4D reprend le contr\xf4le de la gestion des erreurs. En cons\xe9quence, assurez-vous que la m\xe9thode de gestion des erreurs install\xe9e ne puisse pas elle-m\xeame g\xe9n\xe9rer d'erreur. Aussi, vous ne pouvez pas utiliser la commande ",(0,t.jsx)(r.strong,{children:"ON ERR CALL"})," dans une m\xe9thode de gestion des erreurs."]}),"\n",(0,t.jsx)(r.h2,{id:"exemple-1",children:"Exemple 1"}),"\n",(0,t.jsx)(r.p,{children:"Vous souhaitez d\xe9finir un gestionnaire d'erreur global, par exemple dans la m\xe9thode base Sur ouverture :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:'\xa0ON ERR CALL("myGlobalErrorHandler";ek global)\n'})}),"\n",(0,t.jsx)(r.h2,{id:"exemple-2",children:"Exemple 2"}),"\n",(0,t.jsx)(r.p,{children:"La m\xe9thode projet suivante tente de cr\xe9er un document dont le nom est re\xe7u en param\xe8tre et retourne 0 (z\xe9ro) ou un code d'erreur si le document n'a pas pu \xeatre cr\xe9\xe9 :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:'\xa0\xa0// M\xe9thode projet Cr\xe9er doc\n\xa0\xa0// Cr\xe9er doc ( Cha\xeene ; Pointeur ) -> Entier long\n\xa0\xa0// Cr\xe9er doc ( NomDoc ; ->DocRef ) -> Code d\'erreur r\xe9sultant\n\xa0\n\xa0gError:=0\n\xa0ON ERR CALL("IO TRAITEMENT ERREURS")\n\xa0$2->:=Create document($1)\n\xa0ON ERR CALL("")\n\xa0$0:=gError\n'})}),"\n",(0,t.jsx)(r.p,{children:"La m\xe9thode projet IO TRAITEMENT ERREURS est la suivante :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:"\xa0\xa0// M\xe9thode projet IO TRAITEMENT ERREURS\n"})}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:"\xa0gError:=Error\xa0// Simple copie du code d'erreur dans la variable process gError\n"})}),"\n",(0,t.jsxs)(r.p,{children:["Notez l'utilisation de la variable process ",(0,t.jsx)(r.em,{children:"gError"})," pour r\xe9cup\xe9rer le code d'erreur dans la m\xe9thode en train de s'ex\xe9cuter. Une fois que ces m\xe9thodes sont pr\xe9sentes dans votre base, vous pouvez \xe9crire par exemple :"]}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:"\xa0\xa0// ...\n\xa0var vhDocRef : Time\n\xa0$vlErrCode:=Cr\xe9er doc($vsDocumentNom;->vhDocRef)\n\xa0If($vlErrCode=0)\n\xa0\xa0//...\n\xa0\xa0\xa0\xa0CLOSE DOCUMENT($vlErrCode)\n\xa0Else\n\xa0\xa0\xa0\xa0ALERT(\"Le document n'a pas pu \xeatre cr\xe9\xe9, erreur d'E/S \"+String($vlErrCode))\n\xa0End if\n"})}),"\n",(0,t.jsx)(r.h2,{id:"exemple-3",children:"Exemple 3"}),"\n",(0,t.jsxs)(r.p,{children:["Alors que vous impl\xe9mentez un ensemble complexe d'op\xe9rations, vous pouvez terminer avec de multiples sous-routines qui n\xe9cessitent diff\xe9rentes m\xe9thodes de gestion des erreurs. Comme ne pouvez avoir qu'une seule m\xe9thode \xe0 la fois de gestion des erreurs par process, vous devez soit rep\xe9rer la m\xe9thode courante \xe0 chaque fois que vous appelez ",(0,t.jsx)(r.strong,{children:"ON ERR CALL"}),", soit utiliser une variable tableau process (ici ",(0,t.jsx)(r.em,{children:"tabErrorMethod"}),") pour \u201Cempiler\u201D les m\xe9thodes de gestion d'erreur ainsi qu'une m\xe9thode projet (ici APPEL SUR ERR) pour les installer et les d\xe9sinstaller. Le tableau doit \xeatre initialis\xe9 au tout d\xe9but de l'ex\xe9cution du process :"]}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:"\xa0\xa0// N'oubliez pas d'initialiser le tableau au d\xe9but\n\xa0\xa0// de la m\xe9thode de gestion du process\n\xa0ARRAY STRING(63;tabErrorMethod;0)\n"})}),"\n",(0,t.jsx)(r.p,{children:"Voici la m\xe9thode personnalis\xe9e APPEL SUR ERR :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:'\xa0\xa0// M\xe9thode projet APPEL SUR ERR\n\xa0\xa0// APPEL SUR ERR { ( Cha\xeene ) }\n\xa0\xa0// APPEL SUR ERR { ( Nom de la m\xe9thode ) }\n\xa0\n\xa0C_STRING(63;$1;$ErrorMethod)\n\xa0var $vlElem : Integer\n\xa0\n\xa0If(Count parameters>0)\n\xa0\xa0\xa0\xa0$ErrorMethod:=$1\n\xa0Else\n\xa0\xa0\xa0\xa0$ErrorMethod:=""\n\xa0End if\n\xa0\n\xa0If($ErrorMethod#"")\n\xa0\xa0\xa0\xa0var gError : Integer\n\xa0\xa0\xa0\xa0gError:=0\n\xa0\xa0\xa0\xa0$vlElem:=1+Size of array(tabErrorMethod)\n\xa0\xa0\xa0\xa0INSERT IN ARRAY(tabErrorMethod;$vlElem)\n\xa0\xa0\xa0\xa0tabErrorMethod{$vlElem}:=$1\n\xa0\xa0\xa0\xa0ON ERR CALL($1)\n\xa0Else\n\xa0\xa0\xa0\xa0ON ERR CALL("")\n\xa0\xa0\xa0\xa0$vlElem:=Size of array(tabErrorMethod)\n\xa0\xa0\xa0\xa0If($vlElem>0)\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0DELETE FROM ARRAY(tabErrorMethod;$vlElem)\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0If($vlElem>1)\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0ON ERR CALL(tabErrorMethod{$vlElem-1})\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0End if\n\xa0\xa0\xa0\xa0End if\n\xa0End if\n'})}),"\n",(0,t.jsx)(r.p,{children:"Vous pouvez alors l'appeler de la mani\xe8re suivante :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:"\xa0gError:=0\n\xa0APPEL SUR ERR(\"ERREURS ES\")\xa0//Installe la m\xe9thode de gestion d'erreurs ERREURS ES\n\xa0\xa0// ...\n\xa0APPEL SUR ERR(\"TOUTES ERREURS\")\xa0//Installe la m\xe9thode de gestion d'erreurs TOUTES ERREURS\n\xa0\xa0// ...\n\xa0APPEL SUR ERR\xa0//D\xe9sinstalle la m\xe9thode de gestion d'erreurs TOUTES ERREURS et r\xe9installe ERREURS ES\n\xa0\xa0// ...\n\xa0APPEL SUR ERR\xa0//D\xe9sinstalle la m\xe9thode de gestion d'erreurs ERREURS ES\n\xa0\xa0// ...\n"})}),"\n",(0,t.jsx)(r.h2,{id:"exemple-4",children:"Exemple 4"}),"\n",(0,t.jsx)(r.p,{children:"La m\xe9thode de gestion d'erreurs suivante ignore les interruptions de l'utilisateur et affiche le texte de l'erreur :"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-4d",children:'\xa0\xa0//M\xe9thode projet Montrer_seulement_erreurs\n\xa0If(Error#1006)\xa0//ce n\'est pas une interruption utilisateur\n\xa0\xa0\xa0\xa0ALERT("L\'erreur "+String(Error)+" s\'est produite. Le code en cause est : \\""+Error formula+"\\"")\n\xa0End if\n'})}),"\n",(0,t.jsx)(r.h2,{id:"voir-aussi",children:"Voir aussi"}),"\n",(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.a,{href:"/docs/fr/commands/abort",children:"ABORT"}),(0,t.jsx)(r.br,{}),"\n",(0,t.jsx)(r.em,{children:"Gestionnaire d'erreur"}),(0,t.jsx)(r.br,{}),"\n",(0,t.jsx)(r.a,{href:"/docs/fr/commands/last-errors",children:"Last errors"}),(0,t.jsx)(r.br,{}),"\n",(0,t.jsx)(r.a,{href:"/docs/fr/commands/last-errors",children:"Last errors"}),(0,t.jsx)(r.br,{}),"\n",(0,t.jsx)(r.a,{href:"/docs/fr/commands/method-called-on-error",children:"Method called on error"}),(0,t.jsx)(r.br,{}),"\n",(0,t.jsx)(r.em,{children:"Variables syst\xe8me"})]}),"\n",(0,t.jsx)(r.h2,{id:"propri\xe9t\xe9s",children:"Propri\xe9t\xe9s"}),"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",(0,t.jsxs)(r.table,{children:[(0,t.jsx)(r.thead,{children:(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.th,{}),(0,t.jsx)(r.th,{})]})}),(0,t.jsxs)(r.tbody,{children:[(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"Num\xe9ro de commande"}),(0,t.jsx)(r.td,{children:"155"})]}),(0,t.jsxs)(r.tr,{children:[(0,t.jsx)(r.td,{children:"Thread safe"}),(0,t.jsx)(r.td,{children:"\u2713"})]})]})]})]})}function u(e={}){let{wrapper:r}={...(0,o.a)(),...e.components};return r?(0,t.jsx)(r,{...e,children:(0,t.jsx)(c,{...e})}):c(e)}},250065:function(e,r,n){n.d(r,{Z:()=>d,a:()=>l});var s=n(667294);let t={},o=s.createContext(t);function l(e){let r=s.useContext(o);return s.useMemo(function(){return"function"==typeof e?e(r):{...r,...e}},[r,e])}function d(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(t):e.components||t:l(e.components),s.createElement(o.Provider,{value:r},e.children)}}}]);